### ISSUE TITLE
Breaking bug: extension host closed unexpected due to *.less syntax error

### ISSUE THREAD

**Issue by BananaAcid** [Wscats/compile-hero#7]
A syntax error and alike in my main.less is never shown to any VSCode console, but crashes the extension host. The vscode's internal developer console shows a lot of red.

VSCode v.1.43.2
Sass/Less/Typescript/Jade/Pug Compile Hero wscats.qf: v6.8.47

settings.json: disabled everything except for less + pug. (the toggle options set to false)
```
    "compile-hero.jade-output-toggle": false,
    "compile-hero.javascript-output-toggle": true,
    "compile-hero.less-output-toggle": true,
    "compile-hero.pug-output-toggle": true,
    "compile-hero.sass-output-toggle": false,
    "compile-hero.typescript-output-toggle": false,
    "compile-hero.typescriptx-output-toggle": false,
```

complete error info:
``` 
Extension host terminated unexpectedly. Code:  7  Signal:  null
_onExtensionHostCrashed @ abstractExtensionService.ts:155
_onExtensionHostCrashed @ extensionService.ts:379
_onExtensionHostCrashOrExit @ abstractExtensionService.ts:147
(anonymous) @ abstractExtensionService.ts:137
fire @ event.ts:587
_onExtHostProcessExit @ extensionHost.ts:482
(anonymous) @ extensionHost.ts:227
emit @ events.js:203
ChildProcess._handle.onexit @ internal/child_process.js:272


Extension Host >
extensionHost.ts:212 c:\Users\nabil\.vscode\extensions\wscats.qf-6.8.47\out\sass\sass.sync.js:61
var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRO

[TypeError: Cannot read property '0' of undefined
	at hackType (c:\Users\nabil\.vscode\extensions\wscats.qf-6.8.47\node_modules\clean-css\lib\properties\wrap-for-optimizing.js:44:26)
	at wrapSingle (c:\Users\nabil\.vscode\extensions\wscats.qf-6.8.47\node_modules\clean-css\lib\properties\wrap-for-optimizing.js:91:19)
	at wrapAll (c:\Users\nabil\.vscode\extensions\wscats.qf-6.8.47\node_modules\clean-css\lib\properties\wrap-for-optimizing.js:17:18)
	at optimizeBody (c:\Users\nabil\.vscode\extensions\wscats.qf-6.8.47\node_modules\clean-css\lib\selectors\simple.js:297:21)
	at optimize (c:\Users\nabil\.vscode\extensions\wscats.qf-6.8.47\node_modules\clean-css\lib\selectors\simple.js:420:9)
	at optimize (c:\Users\nabil\.vscode\extensions\wscats.qf-6.8.47\node_modules\clean-css\lib\selectors\simple.js:425:9)
	at minify (c:\Users\nabil\.vscode\extensions\wscats.qf-6.8.47\node_modules\clean-css\lib\clean.js:225:3)
	at whenSourceMapReady (c:\Users\nabil\.vscode\extensions\wscats.qf-6.8.47\node_modules\clean-css\lib\clean.js:135:7)
	at Object.whenDone (c:\Users\nabil\.vscode\extensions\wscats.qf-6.8.47\node_modules\clean-css\lib\clean.js:155:14)
	at processNext (c:\Users\nabil\.vscode\extensions\wscats.qf-6.8.47\node_modules\clean-css\lib\imports\inliner.js:105:13)
	at importFrom (c:\Users\nabil\.vscode\extensions\wscats.qf-6.8.47\node_modules\clean-css\lib\imports\inliner.js:79:10)
	at ImportInliner.process (c:\Users\nabil\.vscode\extensions\wscats.qf-6.8.47\node_modules\clean-css\lib\imports\inliner.js:38:10)
	at c:\Users\nabil\.vscode\extensions\wscats.qf-6.8.47\node_modules\clean-css\lib\clean.js:120:41
	at processTicksAndRejections (internal/process/task_queues.js:75:11)]
``` 

TEST IT:
test.less
```
div {
  font-size: 1.em; // 1.0em would be correct
}
```

**Comment by Wscats** [comment]
@BananaAcid Seems to be caused by a sass syntax error, have you modified the sass file?

**Comment by BananaAcid** [comment]
No, as shown above, **NO SASS** enabled, nor used.

**But LESS** ... and each time a **less syntax file error** is encountered on compiling, the **WHOLE EXTENSION-HOST gets crashed** by your VSCode extension ... 

Your extension should output any less compilation error to a CVCode terminal to inform me, where I have a syntax error (missing bracket or alike). And **NOT CRASH on VSCode.**

**Comment by BananaAcid** [comment]
DId you have a chance to see into this?

**Comment by BananaAcid** [comment]
According to the gulp-less documentation [_'By default, emitting an error on a stream will cause it to be thrown unless..'_](https://github.com/gulpjs/gulp/blob/master/docs/recipes/combining-streams-to-handle-errors.md) , a solution might be, to add a try catch block around the less parser:

https://github.com/Wscats/compile-hero/blob/master/vscode-extension/src/extension.ts#L135

**Comment by Wscats** [comment]
@BananaAcid Thank you very much for your reminder, I will add try catch to catch errors.
